let a = "Rahul";
console.log(a)
console.log(a[0])
console.log(a[1])
console.log(a[2])
console.log(a[3])
console.log(a[4])
console.log(a.length)
console.log(a.toUpperCase)
console.log(a.toLowerCase) 
console.log(a.slice(1,4))
console.log(a.replace("Singh","Sing"))
console.log(a.charAt(0))
